import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  photoContent = [
    {id: '1', img: 'assets/west/silver.jpg', showText: 'Silver Falls, OR',
    hideText: 'The South Falls'},
    {id: '2', img: 'assets/east/ny-night.jpg', showText: 'New York City, NY',
    hideText: 'View from top of the Empire State Building'},
    {id: '3', img: 'assets/between/mesa-verde.jpg', showText: 'Mesa Verde, CO',
    hideText: 'The Cliff Palace'},
    {id: '4', img: 'assets/west/weird.jpg', showText: 'Portland, OR',
    hideText: 'Near the original Voodoo Doughnuts'},
    {id: '5', img: 'assets/between/valley-fire.jpg', showText: 'Valley of Fire, NV',
    hideText: 'The Ocean bottom from millions of years ago'},
    {id: '6', img: 'assets/east/ny-bridge.jpg', showText: 'New York City, NY',
    hideText: "That's a Famous Bridge"},
    {id: '7', img: 'assets/between/grand-canyon.jpg', showText: 'Grand Canyon, AZ',
    hideText: 'View from the South Rim'},
    {id: '8', img: 'assets/between/deethstar.jpg', showText: 'Deeth Starr Valley, NV',
    hideText: 'I guess if you live in the middle of nowhere you can call it whatever you want'},
    {id: '9', img: 'assets/between/nowhere.jpg', showText: 'Nowhere or Now Here, NE',
    hideText: 'Embrace the feeling'},
    {id: '10', img: 'assets/east/ny-port.jpg', showText: 'New York City, NY',
    hideText: 'From Liberty Island'},
    {id: '11', img: 'assets/between/valley-road.jpg', showText: 'Kaibab Indian Reservation, AZ',
    hideText: 'On the way to the Grand Canyon'},
    {id: '12', img: 'assets/between/rocky.jpg', showText: 'Klamath, CA',
    hideText: 'Exactly what you think the Pacific should be'},
    {id: '13', img: 'assets/west/grain.jpg', showText: 'Salem, OR',
    hideText: 'Downtown near Riverfront Park'},
    {id: '14', img: 'assets/west/billy-chinnok.jpg', showText: 'Lake Billy Chinook, OR',
    hideText: 'Water does not mess around'},
    {id: '15', img: 'assets/east/niagra2.jpg', showText: 'Buffalo, NY',
    hideText: 'The only time Canada seems trashy, (like putting a McDonalds on the side on the Grand Canyon)'},
    {id: '16', img: 'assets/between/nebr.jpg', showText: 'Near Nebraska City, NE',
    hideText: 'I love the pink granite'},
    {id: '17', img: 'assets/between/arch.jpg', showText: 'Valley of Fire, NV',
    hideText: 'Arch Rock'},
    {id: '18', img: 'assets/between/butte-road.jpg', showText: 'Kaibab Indian Reservation, AZ',
    hideText: 'On the way to the Grand Canyon'},
    {id: '19', img: 'assets/between/butte.jpg', showText: 'Near Urie, WY',
    hideText: 'On the way to SLC'},
    {id: '20', img: 'assets/between/mesa-verde2.jpg', showText: 'Mesa Verde, CO',
    hideText: 'In the Cliff Palace'},
    {id: '21', img: 'assets/between/monument.jpg', showText: 'Near Red Mesa, AZ',
    hideText: 'Near Monument Valley'},
    {id: '22', img: 'assets/between/motel.jpg', showText: 'Rawlins, WY',
    hideText: 'This motel still uses keys, no keycards'},
    {id: '23', img: 'assets/between/rock-art.jpg', showText: 'Valley of Fire, NV',
    hideText: 'Petroglyphs at Atlatl Rock'},
    {id: '24', img: 'assets/between/salt-flat.jpg', showText: 'Great Salt Flats, UT',
    hideText: 'Whole lot of nothing'},
    {id: '25', img: 'assets/between/smokycreek.jpg', showText: 'Gatlinburg, TN',
    hideText: 'Gatlinburg is beautiful -- away from the strip'},
    {id: '26', img: 'assets/between/utah-cap.jpg', showText: 'Salt Lake City, UT',
    hideText: 'State Capital Building SLC'},
    {id: '27', img: 'assets/between/utah.jpg', showText: 'Near Emory, UT',
    hideText: 'The hills east of SLC'},
    {id: '28', img: 'assets/between/valley-fire2.jpg', showText: 'Valley of Fire, NV',
    hideText: "The Valley of Fire is the most desolate place I've ever seen"},
    {id: '29', img: 'assets/between/vegas-tower.jpg', showText: 'Las Vegas, NV',
    hideText: 'Paris in America'},
    {id: '30', img: 'assets/between/zion.jpg', showText: 'Zion, UT',
    hideText: 'Watchman Mountain'},
    {id: '31', img: 'assets/east/bear.jpg', showText: 'Shandaken, NY',
    hideText: 'Curious little bear'},
    {id: '32', img: 'assets/east/camp-falls.jpg', showText: 'Slide Mountain Area, NY',
    hideText: 'I forgot the name of these falls'},
    {id: '33', img: 'assets/east/capital.jpg', showText: 'Washington DC',
    hideText: 'My wife holding up the government'},
    {id: '34', img: 'assets/east/catskills.jpg', showText: 'Shandaken, NY',
    hideText: 'View from the North Dome of Saddle Mountain'},
    {id: '35', img: 'assets/east/grand-central.jpg', showText: 'New York City, NY',
    hideText: 'Grand Central Station'},
    {id: '36', img: 'assets/east/montecello.jpg', showText: 'Charlottesville, VA',
    hideText: "Thomas Jefferson's Monticello"},
    {id: '37', img: 'assets/east/ny-empire.jpg', showText: 'New York City, NY',
    hideText: 'Empire State Building'},
    {id: '38', img: 'assets/east/camp-ndome.jpg', showText: 'Shandaken, NY',
    hideText: 'View of the North Dome of Saddle Mountain'},
    {id: '39', img: 'assets/east/ny-liberty.jpg', showText: 'New York City, NY',
    hideText: 'Lady Liberty'},
    {id: '40', img: 'assets/east/niagra.jpg', showText: 'Buffalo, NY',
    hideText: 'In line for the Hurricane Deck at the Cave of the Winds, Niagra Falls'},
    {id: '41', img: 'assets/east/ny-library.jpg', showText: 'New York City, NY',
    hideText: 'New York Public Library'},
    {id: '42', img: 'assets/east/ny-skyline.jpg', showText: 'New York City, NY',
    hideText: 'Lower Manhattan'},
    {id: '43', img: 'assets/east/penn.jpg', showText: 'Washington DC',
    hideText: '1600 Pennsylvania Ave'},
    {id: '44', img: 'assets/east/ny-tower.jpg', showText: 'New York City, NY',
    hideText: 'One World Trade Center'},
    {id: '45', img: 'assets/east/camp-bball.jpg', showText: 'Shandaken, NY',
    hideText: 'Baseball diamond near Saddle Mountain'},
    {id: '46', img: '', showText: '', hideText: ''},
    {id: '47', img: '', showText: '', hideText: ''},
    {id: '48', img: '', showText: '', hideText: ''},
    {id: '49', img: '', showText: '', hideText: ''},
    {id: '50', img: '', showText: '', hideText: ''},
  ];
}
