import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  photoContent = [
    {id: '1', img: 'assets/west/silver.jpg', showText: 'Silver Falls, OR',
    hideText: 'The South Falls'},
    {id: '2', img: 'assets/east/ny-night.jpg', showText: 'New York City, NY',
    hideText: 'View from top of the Empire State Building'},
    {id: '3', img: 'assets/between/mesa-verde.jpg', showText: 'Mesa Verde, CO',
    hideText: 'The Cliff Palace'},
    {id: '4', img: 'assets/west/weird.jpg', showText: 'Portland, OR',
    hideText: 'Near the original Voodoo Doughnuts'},
    {id: '5', img: 'assets/between/valley-fire.jpg', showText: 'Valley of Fire, NV',
    hideText: 'The Ocean bottom from millions of years ago'},
    {id: '6', img: 'assets/east/ny-bridge.jpg', showText: 'New York City, NY',
    hideText: "That's a Famous Bridge"},
    {id: '7', img: 'assets/between/grand-canyon.jpg', showText: 'Grand Canyon, AZ',
    hideText: 'View from the South Rim'},
    {id: '8', img: 'assets/between/deethstar.jpg', showText: 'Deeth Starr Valley, NV',
    hideText: 'I guess if you live in the middle of nowhere you can call it whatever you want'},
    {id: '9', img: 'assets/between/nowhere.jpg', showText: 'Nowhere or Now Here, NE',
    hideText: 'Embrace the feeling'},
    {id: '10', img: 'assets/east/ny-port.jpg', showText: 'New York City, NY',
    hideText: 'From Liberty Island'},
    {id: '11', img: 'assets/between/valley-road.jpg', showText: 'Kaibab Indian Reservation, AZ',
    hideText: 'On the way to the Grand Canyon'},
    {id: '12', img: 'assets/between/rocky.jpg', showText: 'Klamath, CA',
    hideText: 'Exactly what you think the Pacific should be'},
    {id: '13', img: 'assets/west/grain.jpg', showText: 'Salem, OR',
    hideText: 'Downtown near Riverfront Park'},
    {id: '14', img: 'assets/west/billy-chinnok.jpg', showText: 'Lake Billy Chinook, OR',
    hideText: 'Water does not mess around'},
    {id: '15', img: 'assets/east/niagra2.jpg', showText: 'Buffalo, NY',
    hideText: 'The only time Canada seems trashy, (like putting a McDonalds on the side on the Grand Canyon)'},
    {id: '16', img: '', showText: '', hideText: ''},
    {id: '17', img: '', showText: '', hideText: ''},
    {id: '18', img: '', showText: '', hideText: ''},
    {id: '19', img: '', showText: '', hideText: ''},
    {id: '20', img: '', showText: '', hideText: ''},
    {id: '21', img: '', showText: '', hideText: ''},
    {id: '22', img: '', showText: '', hideText: ''},
    {id: '23', img: '', showText: '', hideText: ''},
    {id: '24', img: '', showText: '', hideText: ''},
    {id: '25', img: '', showText: '', hideText: ''},
    {id: '26', img: '', showText: '', hideText: ''},
    {id: '27', img: '', showText: '', hideText: ''},
    {id: '28', img: '', showText: '', hideText: ''},
    {id: '29', img: '', showText: '', hideText: ''},
    {id: '30', img: '', showText: '', hideText: ''},
  ];
}
